const dotenv = require('dotenv')
dotenv.config()
const express = require('express')
const cors = require('cors')
const ConnectDB = require('./db/db')
const cookieParser = require('cookie-parser')
const app = express()
ConnectDB()
app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use(cookieParser())
app.use(cors())
app.use('/users',require('./routes/user.routes'))
module.exports = app